# topic_selector.py
import random
import datetime
from collections import defaultdict

TOPIC_MAP = {
    0: [  # 월요일
{"board_type": "business", "keyword": "미국 창업자 인터뷰 모음"},
{"board_type": "business", "keyword": "글로벌 셀링을 위한 플랫폼 비교"},
{"board_type": "education", "keyword": "커뮤니티 칼리지와 4년제 대학 비교"},
{"board_type": "education", "keyword": "미국 교육제도 이해하기"},
{"board_type": "freetalk", "keyword": "요즘 빠진 취미 활동"},
{"board_type": "freetalk", "keyword": "미국 생활 중 느낀 사소한 차이들"},
{"board_type": "immigrantlife", "keyword": "영주권 인터뷰 후기"},
{"board_type": "immigrantlife", "keyword": "한인타운 장단점"},
{"board_type": "investment", "keyword": "장기 투자에 적합한 미국 ETF"},
{"board_type": "investment", "keyword": "글로벌 경제지표 해석 방법"},
{"board_type": "jobs", "keyword": "미국 내 경력 전환 스토리"},
{"board_type": "jobs", "keyword": "원격근무 가능한 미국 직업들"},
{"board_type": "legalhelp", "keyword": "H1B 비자 전환 시 주의사항"},
{"board_type": "legalhelp", "keyword": "이민 서류 준비 팁"},
{"board_type": "lifeinfo", "keyword": "미국 생활비 절약 노하우"},
{"board_type": "lifeinfo", "keyword": "처음 가입할 미국 은행 추천"},
{"board_type": "lifestyle", "keyword": "미국 홈데코 트렌드 소개"},
{"board_type": "lifestyle", "keyword": "자연과 함께하는 미국 캠핑 여행"},
{"board_type": "seoul", "keyword": "서울의 디저트 카페 추천"},
{"board_type": "seoul", "keyword": "서울 지하철 타고 떠나는 하루 여행"},
{"board_type": "stock_study", "keyword": "미국 주식 용어 기초 정리"},
{"board_type": "stock_study", "keyword": "초보 투자자를 위한 리스크 관리 팁"},
{"board_type": "korea_realestate", "keyword": "서울과 수도권 집값 비교"},
{"board_type": "korea_realestate", "keyword": "전세 vs 월세, 어떤 게 유리할까?"}           
    ],
    1: [  # 화요일
{"board_type": "business", "keyword": "미국 창업자 인터뷰 모음"},
{"board_type": "business", "keyword": "글로벌 셀링을 위한 플랫폼 비교"},
{"board_type": "education", "keyword": "커뮤니티 칼리지와 4년제 대학 비교"},
{"board_type": "education", "keyword": "미국 교육제도 이해하기"},
{"board_type": "freetalk", "keyword": "요즘 빠진 취미 활동"},
{"board_type": "freetalk", "keyword": "미국 생활 중 느낀 사소한 차이들"},
{"board_type": "immigrantlife", "keyword": "영주권 인터뷰 후기"},
{"board_type": "immigrantlife", "keyword": "한인타운 장단점"},
{"board_type": "investment", "keyword": "장기 투자에 적합한 미국 ETF"},
{"board_type": "investment", "keyword": "글로벌 경제지표 해석 방법"},
{"board_type": "jobs", "keyword": "미국 내 경력 전환 스토리"},
{"board_type": "jobs", "keyword": "원격근무 가능한 미국 직업들"},
{"board_type": "legalhelp", "keyword": "H1B 비자 전환 시 주의사항"},
{"board_type": "legalhelp", "keyword": "이민 서류 준비 팁"},
{"board_type": "lifeinfo", "keyword": "미국 생활비 절약 노하우"},
{"board_type": "lifeinfo", "keyword": "처음 가입할 미국 은행 추천"},
{"board_type": "lifestyle", "keyword": "미국 홈데코 트렌드 소개"},
{"board_type": "lifestyle", "keyword": "자연과 함께하는 미국 캠핑 여행"},
{"board_type": "seoul", "keyword": "서울의 디저트 카페 추천"},
{"board_type": "seoul", "keyword": "서울 지하철 타고 떠나는 하루 여행"},
{"board_type": "stock_study", "keyword": "미국 주식 용어 기초 정리"},
{"board_type": "stock_study", "keyword": "초보 투자자를 위한 리스크 관리 팁"},
{"board_type": "korea_realestate", "keyword": "서울과 수도권 집값 비교"},
{"board_type": "korea_realestate", "keyword": "전세 vs 월세, 어떤 게 유리할까?"}
    ],
    2: [  # 수요일
{"board_type": "business", "keyword": "미국 창업자 인터뷰 모음"},
{"board_type": "business", "keyword": "글로벌 셀링을 위한 플랫폼 비교"},
{"board_type": "education", "keyword": "커뮤니티 칼리지와 4년제 대학 비교"},
{"board_type": "education", "keyword": "미국 교육제도 이해하기"},
{"board_type": "freetalk", "keyword": "요즘 빠진 취미 활동"},
{"board_type": "freetalk", "keyword": "미국 생활 중 느낀 사소한 차이들"},
{"board_type": "immigrantlife", "keyword": "영주권 인터뷰 후기"},
{"board_type": "immigrantlife", "keyword": "한인타운 장단점"},
{"board_type": "investment", "keyword": "장기 투자에 적합한 미국 ETF"},
{"board_type": "investment", "keyword": "글로벌 경제지표 해석 방법"},
{"board_type": "jobs", "keyword": "미국 내 경력 전환 스토리"},
{"board_type": "jobs", "keyword": "원격근무 가능한 미국 직업들"},
{"board_type": "legalhelp", "keyword": "H1B 비자 전환 시 주의사항"},
{"board_type": "legalhelp", "keyword": "이민 서류 준비 팁"},
{"board_type": "lifeinfo", "keyword": "미국 생활비 절약 노하우"},
{"board_type": "lifeinfo", "keyword": "처음 가입할 미국 은행 추천"},
{"board_type": "lifestyle", "keyword": "미국 홈데코 트렌드 소개"},
{"board_type": "lifestyle", "keyword": "자연과 함께하는 미국 캠핑 여행"},
{"board_type": "seoul", "keyword": "서울의 디저트 카페 추천"},
{"board_type": "seoul", "keyword": "서울 지하철 타고 떠나는 하루 여행"},
{"board_type": "stock_study", "keyword": "미국 주식 용어 기초 정리"},
{"board_type": "stock_study", "keyword": "초보 투자자를 위한 리스크 관리 팁"},
{"board_type": "korea_realestate", "keyword": "서울과 수도권 집값 비교"},
{"board_type": "korea_realestate", "keyword": "전세 vs 월세, 어떤 게 유리할까?"}
    ],
    3: [  # 목요일
{"board_type": "business", "keyword": "미국 창업자 인터뷰 모음"},
{"board_type": "business", "keyword": "글로벌 셀링을 위한 플랫폼 비교"},
{"board_type": "education", "keyword": "커뮤니티 칼리지와 4년제 대학 비교"},
{"board_type": "education", "keyword": "미국 교육제도 이해하기"},
{"board_type": "freetalk", "keyword": "요즘 빠진 취미 활동"},
{"board_type": "freetalk", "keyword": "미국 생활 중 느낀 사소한 차이들"},
{"board_type": "immigrantlife", "keyword": "영주권 인터뷰 후기"},
{"board_type": "immigrantlife", "keyword": "한인타운 장단점"},
{"board_type": "investment", "keyword": "장기 투자에 적합한 미국 ETF"},
{"board_type": "investment", "keyword": "글로벌 경제지표 해석 방법"},
{"board_type": "jobs", "keyword": "미국 내 경력 전환 스토리"},
{"board_type": "jobs", "keyword": "원격근무 가능한 미국 직업들"},
{"board_type": "legalhelp", "keyword": "H1B 비자 전환 시 주의사항"},
{"board_type": "legalhelp", "keyword": "이민 서류 준비 팁"},
{"board_type": "lifeinfo", "keyword": "미국 생활비 절약 노하우"},
{"board_type": "lifeinfo", "keyword": "처음 가입할 미국 은행 추천"},
{"board_type": "lifestyle", "keyword": "미국 홈데코 트렌드 소개"},
{"board_type": "lifestyle", "keyword": "자연과 함께하는 미국 캠핑 여행"},
{"board_type": "seoul", "keyword": "서울의 디저트 카페 추천"},
{"board_type": "seoul", "keyword": "서울 지하철 타고 떠나는 하루 여행"},
{"board_type": "stock_study", "keyword": "미국 주식 용어 기초 정리"},
{"board_type": "stock_study", "keyword": "초보 투자자를 위한 리스크 관리 팁"},
{"board_type": "korea_realestate", "keyword": "서울과 수도권 집값 비교"},
{"board_type": "korea_realestate", "keyword": "전세 vs 월세, 어떤 게 유리할까?"}
    ],
    4: [  # 금요일
{"board_type": "business", "keyword": "미국 창업자 인터뷰 모음"},
{"board_type": "business", "keyword": "글로벌 셀링을 위한 플랫폼 비교"},
{"board_type": "education", "keyword": "커뮤니티 칼리지와 4년제 대학 비교"},
{"board_type": "education", "keyword": "미국 교육제도 이해하기"},
{"board_type": "freetalk", "keyword": "요즘 빠진 취미 활동"},
{"board_type": "freetalk", "keyword": "미국 생활 중 느낀 사소한 차이들"},
{"board_type": "immigrantlife", "keyword": "영주권 인터뷰 후기"},
{"board_type": "immigrantlife", "keyword": "한인타운 장단점"},
{"board_type": "investment", "keyword": "장기 투자에 적합한 미국 ETF"},
{"board_type": "investment", "keyword": "글로벌 경제지표 해석 방법"},
{"board_type": "jobs", "keyword": "미국 내 경력 전환 스토리"},
{"board_type": "jobs", "keyword": "원격근무 가능한 미국 직업들"},
{"board_type": "legalhelp", "keyword": "H1B 비자 전환 시 주의사항"},
{"board_type": "legalhelp", "keyword": "이민 서류 준비 팁"},
{"board_type": "lifeinfo", "keyword": "미국 생활비 절약 노하우"},
{"board_type": "lifeinfo", "keyword": "처음 가입할 미국 은행 추천"},
{"board_type": "lifestyle", "keyword": "미국 홈데코 트렌드 소개"},
{"board_type": "lifestyle", "keyword": "자연과 함께하는 미국 캠핑 여행"},
{"board_type": "seoul", "keyword": "서울의 디저트 카페 추천"},
{"board_type": "seoul", "keyword": "서울 지하철 타고 떠나는 하루 여행"},
{"board_type": "stock_study", "keyword": "미국 주식 용어 기초 정리"},
{"board_type": "stock_study", "keyword": "초보 투자자를 위한 리스크 관리 팁"},
{"board_type": "korea_realestate", "keyword": "서울과 수도권 집값 비교"},
{"board_type": "korea_realestate", "keyword": "전세 vs 월세, 어떤 게 유리할까?"}
    ],
    5: [  # 토요일
{"board_type": "business", "keyword": "미국 창업자 인터뷰 모음"},
{"board_type": "business", "keyword": "글로벌 셀링을 위한 플랫폼 비교"},
{"board_type": "education", "keyword": "커뮤니티 칼리지와 4년제 대학 비교"},
{"board_type": "education", "keyword": "미국 교육제도 이해하기"},
{"board_type": "freetalk", "keyword": "요즘 빠진 취미 활동"},
{"board_type": "freetalk", "keyword": "미국 생활 중 느낀 사소한 차이들"},
{"board_type": "immigrantlife", "keyword": "영주권 인터뷰 후기"},
{"board_type": "immigrantlife", "keyword": "한인타운 장단점"},
{"board_type": "investment", "keyword": "장기 투자에 적합한 미국 ETF"},
{"board_type": "investment", "keyword": "글로벌 경제지표 해석 방법"},
{"board_type": "jobs", "keyword": "미국 내 경력 전환 스토리"},
{"board_type": "jobs", "keyword": "원격근무 가능한 미국 직업들"},
{"board_type": "legalhelp", "keyword": "H1B 비자 전환 시 주의사항"},
{"board_type": "legalhelp", "keyword": "이민 서류 준비 팁"},
{"board_type": "lifeinfo", "keyword": "미국 생활비 절약 노하우"},
{"board_type": "lifeinfo", "keyword": "처음 가입할 미국 은행 추천"},
{"board_type": "lifestyle", "keyword": "미국 홈데코 트렌드 소개"},
{"board_type": "lifestyle", "keyword": "자연과 함께하는 미국 캠핑 여행"},
{"board_type": "seoul", "keyword": "서울의 디저트 카페 추천"},
{"board_type": "seoul", "keyword": "서울 지하철 타고 떠나는 하루 여행"},
{"board_type": "stock_study", "keyword": "미국 주식 용어 기초 정리"},
{"board_type": "stock_study", "keyword": "초보 투자자를 위한 리스크 관리 팁"},
{"board_type": "korea_realestate", "keyword": "서울과 수도권 집값 비교"},
{"board_type": "korea_realestate", "keyword": "전세 vs 월세, 어떤 게 유리할까?"}
    ],
    6: [  # 일요일
{"board_type": "business", "keyword": "미국 창업자 인터뷰 모음"},
{"board_type": "business", "keyword": "글로벌 셀링을 위한 플랫폼 비교"},
{"board_type": "education", "keyword": "커뮤니티 칼리지와 4년제 대학 비교"},
{"board_type": "education", "keyword": "미국 교육제도 이해하기"},
{"board_type": "freetalk", "keyword": "요즘 빠진 취미 활동"},
{"board_type": "freetalk", "keyword": "미국 생활 중 느낀 사소한 차이들"},
{"board_type": "immigrantlife", "keyword": "영주권 인터뷰 후기"},
{"board_type": "immigrantlife", "keyword": "한인타운 장단점"},
{"board_type": "investment", "keyword": "장기 투자에 적합한 미국 ETF"},
{"board_type": "investment", "keyword": "글로벌 경제지표 해석 방법"},
{"board_type": "jobs", "keyword": "미국 내 경력 전환 스토리"},
{"board_type": "jobs", "keyword": "원격근무 가능한 미국 직업들"},
{"board_type": "legalhelp", "keyword": "H1B 비자 전환 시 주의사항"},
{"board_type": "legalhelp", "keyword": "이민 서류 준비 팁"},
{"board_type": "lifeinfo", "keyword": "미국 생활비 절약 노하우"},
{"board_type": "lifeinfo", "keyword": "처음 가입할 미국 은행 추천"},
{"board_type": "lifestyle", "keyword": "미국 홈데코 트렌드 소개"},
{"board_type": "lifestyle", "keyword": "자연과 함께하는 미국 캠핑 여행"},
{"board_type": "seoul", "keyword": "서울의 디저트 카페 추천"},
{"board_type": "seoul", "keyword": "서울 지하철 타고 떠나는 하루 여행"},
{"board_type": "stock_study", "keyword": "미국 주식 용어 기초 정리"},
{"board_type": "stock_study", "keyword": "초보 투자자를 위한 리스크 관리 팁"},
{"board_type": "korea_realestate", "keyword": "서울과 수도권 집값 비교"},
{"board_type": "korea_realestate", "keyword": "전세 vs 월세, 어떤 게 유리할까?"}
    ],
}

def get_random_topic():
    today = datetime.datetime.today().weekday()
    today_topics = TOPIC_MAP.get(today, [])

    if not today_topics:
        return []

    # 게시판(board_type)별로 묶기
    grouped = defaultdict(list)
    for topic in today_topics:
        grouped[topic['board_type']].append(topic)

    # 각 게시판에서 하나씩 랜덤 선택
    selected = [random.choice(topics) for topics in grouped.values()]
    return selected
