# topic_selector.py
import random
import datetime
from collections import defaultdict

TOPIC_MAP = {
    0: [  # 월요일
        {"board_type": "business", "keyword": "미국 소자본으로 창업하기"},
        {"board_type": "business", "keyword": "온라인 비즈니스 시작하기"},
        {"board_type": "education", "keyword": "미국 교육제도 이해"},
        {"board_type": "education", "keyword": "미국 명문대 입학 조건"},
        {"board_type": "freetalk", "keyword": "미국 요즘 화제"},
        {"board_type": "freetalk", "keyword": "미국 정치 뉴스"},
        {"board_type": "immigrantlife", "keyword": "이민 정착 관련 뉴스"},
        {"board_type": "immigrantlife", "keyword": "생활 정착 & 문화 차이"},
        {"board_type": "investment", "keyword": "경제 지표와 투자 신호를 읽어내는 인사이트 채널/서비스"},
        {"board_type": "investment", "keyword": "장기적 관점에서 스마트하게 알파(초과 수익)를 추구하는 전략"},
        {"board_type": "jobs", "keyword": ""},
        {"board_type": "jobs", "keyword": ""}, 
        {"board_type": "legalhelp", "keyword": ""},
        {"board_type": "legalhelp", "keyword": ""},
        {"board_type": "lifeinfo", "keyword": ""},
        {"board_type": "lifeinfo", "keyword": ""},
        {"board_type": "lifestyle", "keyword": ""},
        {"board_type": "lifestyle", "keyword": ""},               
    ],
    1: [  # 화요일
        {"board_type": "business", "keyword": "미국 프랜차이즈 추천"},
        {"board_type": "business", "keyword": "마케팅 자동화 툴"},
        {"board_type": "education", "keyword": "미국 공립학교 vs 사립학교"},
        {"board_type": "education", "keyword": "UC 계열 진학 정보"},
        {"board_type": "freetalk", "keyword": "미국 사회 이슈"},
        {"board_type": "freetalk", "keyword": "오늘의 핫이슈"},
        {"board_type": "immigrantlife", "keyword": "이민 1세대 이야기"},
        {"board_type": "immigrantlife", "keyword": "미국 이민 현실 브이로그"},
        {"board_type": "investment", "keyword": "하루 3분, 전 세계 거시경제를 읽는 요약 콘텐츠"},
        {"board_type": "investment", "keyword": "미국 주식 투자 전략 올해 전략"},
        {"board_type": "jobs", "keyword": "미국 취업 비자 현실과 팁"},
        {"board_type": "jobs", "keyword": "미국에서 잘 나가는 직업 Top 10"}, 
        {"board_type": "legalhelp", "keyword": "미국 영주권 최신 소식 올해"},
        {"board_type": "legalhelp", "keyword": "이민 변호사 없이 신청하는 미국 비자"},
        {"board_type": "lifeinfo", "keyword": "미국에서 처음 살 때 꼭 알아야 할 것들"},
        {"board_type": "lifeinfo", "keyword": "2025년 미국 마트 장보기 비용 공개"},
        {"board_type": "lifestyle", "keyword": "미국 로드트립 추천 코스"},
        {"board_type": "lifestyle", "keyword": "여름방학 미국 가족 여행 추천 장소"},
    ],
    2: [  # 수요일
        {"board_type": "business", "keyword": "ChatGPT 사업 아이디어"},
        {"board_type": "business", "keyword": "한인 대상 비즈니스"},
        {"board_type": "education", "keyword": "미국 중고등학교 생활"},
        {"board_type": "education", "keyword": "SAT vs ACT 준비법"},
        {"board_type": "freetalk", "keyword": "미국에서 인기 있는 콘텐츠"},
        {"board_type": "freetalk", "keyword": "한국 최신 트렌드"},
        {"board_type": "immigrantlife", "keyword": "미국 금리"},
        {"board_type": "immigrantlife", "keyword": "연준 발표"},
        {"board_type": "investment", "keyword": "미국 채권시장"},
        {"board_type": "investment", "keyword": "미국 금리"},
        {"board_type": "jobs", "keyword": "연준 발표"},
        {"board_type": "jobs", "keyword": "미국 채권시장"}, 
        {"board_type": "legalhelp", "keyword": "미국 금리"},
        {"board_type": "legalhelp", "keyword": "연준 발표"},
        {"board_type": "lifeinfo", "keyword": "미국 채권시장"},
        {"board_type": "lifeinfo", "keyword": "미국 금리"},
        {"board_type": "lifestyle", "keyword": "연준 발표"},
        {"board_type": "lifestyle", "keyword": "미국 채권시장"},
    ],
    3: [  # 목요일
        {"board_type": "business", "keyword": "OC에서 할만한 사업"},
        {"board_type": "business", "keyword": "이민자 창업 성공 사례"},
        {"board_type": "education", "keyword": "미국 대학 입시 제도"},
        {"board_type": "education", "keyword": "미국 초등학생 공부 습관"},
        {"board_type": "freetalk", "keyword": "미국 라이프스타일 브이로그"},
        {"board_type": "freetalk", "keyword": "요즘 유행하는 챌린지"},
        {"board_type": "immigrantlife", "keyword": "미국 금리"},
        {"board_type": "immigrantlife", "keyword": "연준 발표"},
        {"board_type": "investment", "keyword": "미국 채권시장"},
        {"board_type": "investment", "keyword": "미국 금리"},
        {"board_type": "jobs", "keyword": "연준 발표"},
        {"board_type": "jobs", "keyword": "미국 채권시장"}, 
        {"board_type": "legalhelp", "keyword": "미국 금리"},
        {"board_type": "legalhelp", "keyword": "연준 발표"},
        {"board_type": "lifeinfo", "keyword": "미국 채권시장"},
        {"board_type": "lifeinfo", "keyword": "미국 금리"},
        {"board_type": "lifestyle", "keyword": "연준 발표"},
        {"board_type": "lifestyle", "keyword": "미국 채권시장"},
    ],
    4: [  # 금요일
        {"board_type": "business", "keyword": "미국 사업자 세금 절세"},
        {"board_type": "business", "keyword": "유튜브 수익화 전략"},
        {"board_type": "education", "keyword": "대입 에세이 작성 요령"},
        {"board_type": "education", "keyword": "자녀 이중언어 교육 방법"},
        {"board_type": "freetalk", "keyword": "인생 조언 영상"},
        {"board_type": "freetalk", "keyword": "힐링 브이로그"},
        {"board_type": "immigrantlife", "keyword": "미국 금리"},
        {"board_type": "immigrantlife", "keyword": "연준 발표"},
        {"board_type": "investment", "keyword": "미국 채권시장"},
        {"board_type": "investment", "keyword": "미국 금리"},
        {"board_type": "jobs", "keyword": "연준 발표"},
        {"board_type": "jobs", "keyword": "미국 채권시장"}, 
        {"board_type": "legalhelp", "keyword": "미국 금리"},
        {"board_type": "legalhelp", "keyword": "연준 발표"},
        {"board_type": "lifeinfo", "keyword": "미국 채권시장"},
        {"board_type": "lifeinfo", "keyword": "미국 금리"},
        {"board_type": "lifestyle", "keyword": "연준 발표"},
        {"board_type": "lifestyle", "keyword": "미국 채권시장"},
    ],
    5: [  # 토요일
        {"board_type": "business", "keyword": "블로그 자동 수익 시스템"},
        {"board_type": "business", "keyword": "한인 마켓 트렌드"},
        {"board_type": "education", "keyword": "학습동기 부여 방법"},
        {"board_type": "education", "keyword": "부모가 도와줄 수 있는 교육법"},
        {"board_type": "freetalk", "keyword": "요즘 핫한 예능"},
        {"board_type": "freetalk", "keyword": "하루 루틴 영상"},
        {"board_type": "immigrantlife", "keyword": "미국 이민자 이야기"},
        {"board_type": "immigrantlife", "keyword": "미국 이민 브이로그"},
        {"board_type": "investment", "keyword": "미국 주식 전망"},
        {"board_type": "investment", "keyword": "자산 배분 전략"},
        {"board_type": "jobs", "keyword": "미국 직장인 브이로그"},
        {"board_type": "jobs", "keyword": "미국 취업 인터뷰 팁"},
        {"board_type": "legalhelp", "keyword": "미국 영주권 법률 정보"},
        {"board_type": "legalhelp", "keyword": "이민 변호사 상담"},
        {"board_type": "lifeinfo", "keyword": "미국 생활 꿀팁"},
        {"board_type": "lifeinfo", "keyword": "한인 마트 추천"},
        {"board_type": "lifestyle", "keyword": "미국 일상 브이로그"},
        {"board_type": "lifestyle", "keyword": "미국에서의 주말"}
    ],
    6: [  # 일요일
        {"board_type": "business", "keyword": "디지털 상품 판매"},
        {"board_type": "business", "keyword": "온라인 강의 플랫폼 운영"},
        {"board_type": "education", "keyword": "과외활동 포트폴리오"},
        {"board_type": "education", "keyword": "유학생활 적응기"},
        {"board_type": "freetalk", "keyword": "미국 마트 장보기"},
        {"board_type": "freetalk", "keyword": "걷기 명상 영상"},
        {"board_type": "immigrantlife", "keyword": "미국 금리"},
        {"board_type": "immigrantlife", "keyword": "연준 발표"},
        {"board_type": "investment", "keyword": "미국 채권시장"},
        {"board_type": "investment", "keyword": "미국 금리"},
        {"board_type": "jobs", "keyword": "연준 발표"},
        {"board_type": "jobs", "keyword": "미국 채권시장"}, 
        {"board_type": "legalhelp", "keyword": "미국 금리"},
        {"board_type": "legalhelp", "keyword": "연준 발표"},
        {"board_type": "lifeinfo", "keyword": "미국 채권시장"},
        {"board_type": "lifeinfo", "keyword": "미국 금리"},
        {"board_type": "lifestyle", "keyword": "연준 발표"},
        {"board_type": "lifestyle", "keyword": "미국 채권시장"},
    ],
}

def get_random_topic():
    today = datetime.datetime.today().weekday()
    today_topics = TOPIC_MAP.get(today, [])

    if not today_topics:
        return []

    # 게시판(board_type)별로 묶기
    grouped = defaultdict(list)
    for topic in today_topics:
        grouped[topic['board_type']].append(topic)

    # 각 게시판에서 하나씩 랜덤 선택
    selected = [random.choice(topics) for topics in grouped.values()]
    return selected
